# Generated by Django 3.2.5 on 2021-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
