# Generated by Django 3.2.5 on 2021-07-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_articles_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='viewList',
            field=models.TextField(default='[]'),
        ),
    ]
