# Generated by Django 3.2.5 on 2021-07-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_articles_viewlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='viewList',
            field=models.TextField(default=[]),
        ),
    ]
